### ISSUE TITLE
Extended isolation forests in R

### ISSUE THREAD

**Issue by ergodiclife** [pridiltal/ctv-AnomalyDetection#2]
Hey Priyanga,

I wrote an R wrapper around the eif Python package for creating Extended Isolation Forests here: https://github.com/ergodiclife/eif. I'd love your feedback and for it to be added to your task view if you're happy with it :)

**Comment by pridiltal** [comment]
Hey ergodiclife

This is great Thanks so much for this 📦. Do you have any plans to submit to CRAN yet? I think I should add a new section for packages on GitHub. There are really useful package on GitHub for anomaly detection. I'll add a new section an update you soon.

**Comment by ergodiclife** [comment]
I'll chuck it on CRAN soon :)
